require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/bin/**/*

RSpec/ExampleLength:
  Exclude:
    - spec/bin/**/*

Metrics/AbcSize:
  Max: 25
